[package]
name = "tpm2-rs-errors"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]

# Provide conversion to/from std error types
std = []

# Includes debug trait implementation. Useful for unit tests.
debug = []

[dependencies]
